version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:${SERVER_PORT}"
      - "--providers.file.directory=/configuration"
      - "--providers.file.watch=true"
    ports:
      - "8082:8082"
      - "8080:8080"
    networks:
      - backend
      - traefik-public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${TRAEFIK_CONFIG}:/configuration/"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    networks:
      - backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  fast:
    image: fast:latest
    build: ./app/
    #container_name: "fast"
    env_file:
      - ./.env
    networks:
      - backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fast.rule=Host(`${SERVER_HOST}`)"
      - "traefik.http.routers.fast.entrypoints=web"
      - "traefik.http.routers.fast.tls=true"
      - "traefik.http.middlewares.addHeader.headers.accesscontrolallowmethods=GET,POST,OPTIONS,PUT"
      - "traefik.http.middlewares.addHeader.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.addHeader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.addHeader.headers.addvaryheader=true"
      - "traefik.http.routers.fast.middlewares=addHeader"
    volumes:
      - ./app:/app/app
      - ./images:/images
      - ./script:/script
      - ./static-files:/static-files
    entrypoint: /start-reload.sh

  redis:
    image: redis:6
    restart: always
    container_name: "redis"
    # ports:
    #   - "6379:6379"
    # networks:
    #   - backend
    # labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.redis.rule=Host(`redis.localhost`)"
      # - "traefik.http.routers.whoami.entrypoints=web"
      
    # launch Redis in cache mode with :
    #  - max memory up to 50% of your RAM if needed (--maxmemory 512mb)
    #  - deleting oldest data when max memory is reached (--maxmemory-policy allkeys-lru)
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`redis.localhost`)"
      - "traefik.port=${REDIS_PORT}"
    entrypoint: redis-server --maxmemory 2048mb --maxmemory-policy allkeys-lru
 
  modelserv_yolov5:
    image: modelserv_yolov5:latest
    build: 
      context: .
      dockerfile: ./modelserv/model_yolov5/Dockerfile

    #container_name: "modelserv"
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ['0']
    networks:
      - backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.modelserv_yolov5.rule=Host(`modelserv_yolov5.localhost`)"
      - "traefik.http.routers.modelserv_yolov5.entrypoints=web"
    volumes:
      - ./images:/images
      - ./script:/script

  modelserv_detectron2:
    image: modelserv_detectron2:latest
    build: 
      context: .
      dockerfile: ./modelserv/model_detectron2/Dockerfile
    #container_name: "modelserv"
    env_file:
      - ./.env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ['0']
    networks:
      - backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.modelserv.rule=Host(`modelserv_detectron2.localhost`)"
      - "traefik.http.routers.modelserv.entrypoints=web"
    volumes:
      - ./images:/images
      - ./script:/script

networks:
  traefik-public:
    external: true
  backend:
    external: false
