version: "3.3"

services:

  modelserv:
    image: modelserv:latest
    build:
      context: ../../
      dockerfile: ./modelserv/model_detectron2/Dockerfile
    #container_name: "modelserv"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ['1']
    networks:
      - keras-model-server-fast-api_backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.modelserv.rule=Host(`modelserv.localhost`)"
      - "traefik.http.routers.modelserv.entrypoints=web"
    volumes:
      - ./images:/images
      - ./script:/script

networks:
  traefik-public:
    external: True
  keras-model-server-fast-api_backend:
    external: True

# Use this command. Note that the -p switch tells it it's a separate project from the main API, so you have to use the networks definitions above to be able to use service discovery. You also need to run this command from the main repo directory because of docker context nonsense.

# docker-compose -f ./modelserv/model_detectron2/docker-compose-model-worker.yml -p model-workers up --build modelserv